org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dhttp.socketTimeout=60000 -Dhttps.socketTimeout=60000
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.useAndroidX=true
android.enableJetifier=true